language: node_js
node_js:
- '4.1'
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
  - vendor
before_install:
  - rvm install `cat .ruby-version`
  - gem install bundler
install:
  - npm install
script:
  - npm run-script build
after_success:
  - npm run-script deploy
env:
  - CXX=g++-4.8
  - AWS_S3_BUCKET=s3.fightforthefuture.org
  - AWS_S3_FOLDER=images/blog
  - PETITIONS_API=https://info.fightforthefuture.org
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
branches:
  only:
    - production
