#################################################
# Config: Development                           #
#################################################
# (production settings go in _config.build.yml) #

#############
# Meta info #
#############

name: Fight for the Future, defending our basic rights and freedoms
url: https://www.fightforthefuture.org
description: "Fight for the Future is dedicated to protecting and expanding the Internet's transformative power in our lives by creating civic campaigns that are engaging for millions of people."
timezone: America/New_York
googleanalytics: UA-26576645-1
anapi: d91e5e9ad3ce422c8d114899594bb0ba

favicon: '/homepage/images/heart.png' # replace this with path to favicon if that’s a thing you’re doing.

author:
    googleid: 102356128596404327231
    twitterid: 382376904
    twitter: fightfortheftr

#############
# Authoring #
#############

future: true
show_drafts: true
permalink: /:categories/:title/

collections:
  legacy_pages:
    output: true
    permalink: /:path/
  petitions:
    output: true
    permalink: /:categories/:path/
  redirects:
    output: true
    permalink: /:title/
  static_pages:
    output: true
    permalink: /:path/

prose:
  rooturl: 'site'
  ignore:
    - '_includes'
    - '_js'
    - '_layouts'
    - '_less'
    - '_plugins'
    - 'brand'
    - 'branding'
    - 'css'
    - 'js'
    - 'webfonts'
    - 'google5033d6ab2e00df50.html'
    - 'robots.txt'
    - 'sitemap.xml'
    - 'style.css'

  siteurl: 'https://www.fightforthefuture.org'
  media: 'site/img'
  metadata:
    '':
      - name: "title"
        field:
          element: "text"
          label: "title"
          value: ''
    'site/_petitions':
      - name: 'title'
        field:
          element: 'text'
          label: 'title'
          value: ''
      - name: 'headline'
        field:
          element: 'text'
          label: 'Page headline'
          placeholder: 'President Obama is withholding free pizza. Put a stop to it now.'
      - name: 'petition-slug'
        field:
          element: 'text'
          label: 'Petition slug'
          helper: 'If your petition url is https://actionnetwork.org/petitions/my-petition-title then your slug is my-petition-title'
          placeholder: 'free-pizza-day'
      - name: 'petition-title'
        field:
          element: 'text'
          label: 'Petition title'
          placeholder: 'Tell President Obama:'
      - name: 'petition-copy'
        field:
          element: 'textarea'
          label: 'Petition copy'
          placeholder: 'Fridays should be free pizza day. Push legislation today to bring pizza into the lives of all Americans!'
      - name: 'default-donation-amount'
        field:
          element: 'number'
          label: 'Default donation amount'
          help: 'Dollar amount in the top right corner donation link'
          value: '5'
      - name: 'default-donation-frequency'
        field:
          element: 'select'
          label: 'Default donation frequency'
          help: 'Donation frequency for donation link'
          options:
            - name: Once
              value: 'just-once'
            - name: Monthly
              value: monthly
            - name: Annual
              value: annual

#############
# Compiling #
#############

exclude: ['img', 'images', 'css', 'js']
keep_files: ['img', 'images', 'css', 'js']


# this is commented bc each page has its own assets O_O
#exclude: [
#  'img', 'css', 'fonts', '**.haml',
#  '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico',
#]
#

highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
