######################
# Config: Production #
######################

#############
# Meta info #
#############

petitions_api: https://info.fightforthefuture.org

#############
# Authoring #
#############

future: false
show_drafts: false
production: true
