version: 2
jobs:
  build:
    docker:
      # circleci/ruby:2.4-node-browsers + awscli
       - image: kenmickles/fftf-static-site-builder:0.0.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "package-lock.json" }}

      - run:
          name: install dependencies
          command: |
            bundle install --path vendor/bundle
            npm install

      - save_cache:
          paths:
            - ./vendor/bundle
            - node_modules
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "package-lock.json" }}

      - run:
          name: build
          command: |
            npm run build

      - deploy:
          name: Deploy to S3
          command: |
            aws s3 sync public s3://s3-test2.fightforthefuture.org --delete
workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only: production